# Conda environment that include all dependencies for PyCapsid
# with explicit versions

name: pycapsid_HPC

channels:
  - luque_lab
  - conda-forge
  - defaults

dependencies:
  - python=3.10.0
  - biotite=0.39.0
  - numpy=1.21.4
  - pandas=1.3.4
  - matplotlib=3.4.3
  - scipy=1.7.1
  - scikit-learn=0.24.2
  - requests=2.26.0
  - pytest=6.2.5 
  - pycapsid=0.5.9
