name: Conda Package Custom Publish

on:
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: conda-incubator/setup-miniconda@v2
          with:
            miniconda-version: "latest"
            activate-environment: build
      - name: conda-setup
        shell: bash
        run: conda install conda-build anaconda-client
      - name: publish-to-conda-custom
        shell: bash
        run: |
          cd conda
          conda build -c conda-forge --output-folder . .
          export ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
          anaconda upload --label main noarch/*.tar.bz2
