name: Conda Package Custom Publish

on:
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: build
      - name: conda-setup
        shell: bash -el {0}
        run: |
          conda install conda-build 
      - name: publish-to-conda-custom
        shell: bash -el {0}
        run: |
          cd conda
          conda build -c conda-forge --output-folder . .
          conda install anaconda-client
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --label main noarch/*.tar.bz2
