name: Publish Conda Package

on: 
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install git
      run: |
        conda install -c anaconda git
    - name: publish-to-conda
      uses: fcakyon/conda-publish-action@master
      with:
        subdir: '.'
        anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
        platforms: ''
