[PDB]
pdb = '1a34'
pdbx = false
local = false
dir = '.'
save_full_pdb = false
save_pdb_path = '.'

[CG]
preset = 'U-ENM'
save_hessian = false
save_kirchhoff = false
save_cg_path = '.'

[NMA]
n_modes = 200
eigen_method = 'eigsh'
shift_invert = true
save_modes = false
save_mode_path = '.'

[b_factors]
fit_modes = false
plot_modes = false
force_ico = true
ico_tol = 0.002
save_bfactors = false
save_bfactors_path = '.'


[QRC]
cluster_start = 10
cluster_stop = 100
cluster_step = 2
cluster_method = 'discretize'
score_method = 'median'
save_results =  true
save_results_path =  ''

[VIS]
chimerax_path = 'C:\\Program Files\\ChimeraX\\bin\\ChimeraX.exe'


